export const SET_USER = "SET_USER";
export const START_SET_USER = "START_SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const FETCH_FRIENDS = "FETCH_FRIENDS";
export const SET_SELECTED_FRIEND = "SET_SELECTED_FRIEND";
export const SAVE_GIFT = "SAVE_GIFT";
export const SET_SELECTED_OCCASION = "SET_SELECTED_OCCASION";
export const FETCH_OCCASIONS = "FETCH_OCCASIONS";
